######################################################################
# Automatically generated by qmake (3.0) ?? 9? 8 14:44:32 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp




