######################################################################
# Automatically generated by qmake (3.0) ?? 9? 8 15:30:23 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Button
INCLUDEPATH += .

# Input
SOURCES += Button.cpp
